package org.omg.DynamicAny;


/**
* org/omg/DynamicAny/DynEnumOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /scratch/opt/mach5/mesos/work_dir/slaves/5af44a71-976a-41b7-81de-5773b84ec572-S39643/frameworks/1735e8a2-a1db-478c-8104-60c8b0af87dd-0196/executors/a3f74ad9-294f-4385-b9cc-31da721d8f41/runs/504babbb-611e-4037-9ed3-2563bc56551c/workspace/corba/src/java.corba/share/classes/org/omg/DynamicAny/DynamicAny.idl
* Tuesday, December 19, 2017 6:09:03 PM PST
*/


/**
    * DynEnum objects support the manipulation of IDL enumerated values.
    * The current position of a DynEnum is always -1.
    */
public interface DynEnumOperations  extends org.omg.DynamicAny.DynAnyOperations
{

  /**
          * Returns the value of the DynEnum as an IDL identifier.
          */
  String get_as_string ();

  /**
          * Sets the value of the DynEnum to the enumerated value whose IDL identifier is passed in the value parameter.
          *
          * @exception InvalidValue If value contains a string that is not a valid IDL identifier
          *            for the corresponding enumerated type
          */
  void set_as_string (String value) throws org.omg.DynamicAny.DynAnyPackage.InvalidValue;

  /**
          * Returns the value of the DynEnum as the enumerated value's ordinal value.
          * Enumerators have ordinal values 0 to n-1, as they appear from left to right
          * in the corresponding IDL definition.
          */
  int get_as_ulong ();

  /**
          * Sets the value of the DynEnum as the enumerated value's ordinal value.
          *
          * @exception InvalidValue If value contains a value that is outside the range of ordinal values
          *            for the corresponding enumerated type
          */
  void set_as_ulong (int value) throws org.omg.DynamicAny.DynAnyPackage.InvalidValue;
} // interface DynEnumOperations
