package org.omg.IOP;


/**
* org/omg/IOP/TAG_ORB_TYPE.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /scratch/opt/mach5/mesos/work_dir/slaves/5af44a71-976a-41b7-81de-5773b84ec572-S39643/frameworks/1735e8a2-a1db-478c-8104-60c8b0af87dd-0196/executors/a3f74ad9-294f-4385-b9cc-31da721d8f41/runs/504babbb-611e-4037-9ed3-2563bc56551c/workspace/corba/src/java.corba/share/classes/org/omg/PortableInterceptor/IOP.idl
* Tuesday, December 19, 2017 6:09:04 PM PST
*/

public interface TAG_ORB_TYPE
{

  /**
       * It is often useful in the real world to be able to identify the 
       * particular kind of ORB an object reference is coming from, to work 
       * around problems with that particular ORB, or exploit shared 
       * efficiencies. 
       * <p>
       * The <code>TAG_ORB_TYPE</code> component has an associated value of 
       * type unsigned long (Java long), encoded as a CDR encapsulation, 
       * designating an ORB type ID allocated by the OMG for the ORB type of the 
       * originating ORB. Anyone may register any ORB types by submitting 
       * a short (one-paragraph) description of the ORB type to the OMG, 
       * and will receive a new ORB type ID in return. A list of ORB type 
       * descriptions and values will be made available on the OMG web server. 
       * <p>
       * The <code>TAG_ORB_TYPE</code> component can appear at most once in 
       * any IOR profile. For profiles supporting IIOP 1.1 or greater, it 
       * is optionally present.
       */
  public static final int value = (int)(0L);
}
